# -*- coding: utf-8 -*-
"""v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zbZyh7hDTxPCZFwUHlwre9O_Ds6M1hV
"""

import os
import zipfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices("GPU"))

LATENT_DIM = 256
INPUT_SHAPE = (227, 227, 1)
BATCH_SIZE = 32
EPOCHS = 50

from google.colab import files
uploaded = files.upload()

# ============================================================
# DATASET PATHS
# ============================================================

DATASET_ROOT = "/content/NSSC_HiRISE.zip"

TRAIN_DIR = os.path.join(DATASET_ROOT, "train", "normal")
VAL_DIR   = os.path.join(DATASET_ROOT, "validation", "normal")
TEST_DIR  = os.path.join(DATASET_ROOT, "test", "normal")

print("Dataset root:", DATASET_ROOT)
print("Train:", TRAIN_DIR)
print("Val  :", VAL_DIR)
print("Test :", TEST_DIR)

import os
import zipfile

# =========================
# 1. ZIP PATH
# =========================
ZIP_PATH = "/content/NSSC_HiRISE.zip"
EXTRACT_DIR = "/content/NSSC_HiRISE"

# =========================
# 2. EXTRACT ZIP
# =========================
if not os.path.exists(EXTRACT_DIR):
    print("Extracting ZIP...")
    with zipfile.ZipFile(ZIP_PATH, "r") as zip_ref:
        zip_ref.extractall(EXTRACT_DIR)
    print("Extraction complete!")
else:
    print("Already extracted.")

# =========================
# 3. CHECK STRUCTURE
# =========================
for root, dirs, files in os.walk(EXTRACT_DIR):
    level = root.replace(EXTRACT_DIR, "").count(os.sep)
    if level <= 2:
        print("  " * level + os.path.basename(root) + "/")

# =========================
# 4. FIND TRAIN / VAL / TEST
# =========================
def find_dir(name):
    for root, dirs, files in os.walk(EXTRACT_DIR):
        if os.path.basename(root).lower() == name.lower():
            return root
    return None

TRAIN_DIR = find_dir("train")
VAL_DIR   = find_dir("val")
TEST_DIR  = find_dir("test")

print("\nTRAIN:", TRAIN_DIR)
print("VAL  :", VAL_DIR)
print("TEST :", TEST_DIR)

# =========================
# 5. LIST JPG FILES
# =========================
def list_jpgs(directory):
    if directory is None:
        return []

    return sorted([
        os.path.join(root, f)
        for root, dirs, files in os.walk(directory)
        for f in files
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ])

train_files = list_jpgs(TRAIN_DIR)
val_files   = list_jpgs(VAL_DIR)
test_files  = list_jpgs(TEST_DIR)

print("\n==============================")
print("DATASET FILE COUNT")
print("==============================")
print("Train:", len(train_files))
print("Val  :", len(val_files))
print("Test :", len(test_files))

print("\nExample:")
print(train_files[:5])

import os
import zipfile

ZIP_PATH = "/content/NSSC_HiRISE.zip"

print("ZIP exists:", os.path.exists(ZIP_PATH))
print("ZIP size:", os.path.getsize(ZIP_PATH) / (1024**2), "MB")

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    files = z.namelist()

print("\nTotal ZIP entries:", len(files))

print("\n========== FIRST 100 ENTRIES ==========")
for x in files[:100]:
    print(x)

print("\n========== IMAGE COUNT ==========")

images = [
    x for x in files
    if x.lower().endswith((".jpg", ".jpeg", ".png", ".webp"))
]

print("Total images:", len(images))

print("\n========== IMAGE FOLDERS ==========")

folders = {}

for img in images:
    folder = os.path.dirname(img)
    folders[folder] = folders.get(folder, 0) + 1

for folder, count in sorted(folders.items(), key=lambda x: -x[1]):
    print(f"{count:6d} images  ->  {folder}")

import os

# ============================================================
# NSSC HiRISE V2 - AUTO DATASET PATH DETECTION
# ============================================================

SEARCH_ROOT = "/content"

def find_folder(folder_name):
    matches = []

    for root, dirs, files in os.walk(SEARCH_ROOT):
        if os.path.basename(root).lower() == folder_name.lower():
            matches.append(root)

    return matches


# ------------------------------------------------------------
# Find required folders automatically
# ------------------------------------------------------------

train_candidates = find_folder("train")
validation_candidates = find_folder("validation")
test_candidates = find_folder("test")
original_candidates = find_folder("original_untouched")

print("TRAIN candidates:")
for x in train_candidates:
    print(" ", x)

print("\nVALIDATION candidates:")
for x in validation_candidates:
    print(" ", x)

print("\nTEST candidates:")
for x in test_candidates:
    print(" ", x)

print("\nORIGINAL candidates:")
for x in original_candidates:
    print(" ", x)


# ------------------------------------------------------------
# Select folders containing actual images
# ------------------------------------------------------------

def choose_folder(candidates, required_subfolder=None):

    for folder in candidates:

        target = folder

        if required_subfolder:
            target = os.path.join(folder, required_subfolder)

        if os.path.isdir(target):

            images = [
                f for f in os.listdir(target)
                if f.lower().endswith(
                    (".jpg", ".jpeg", ".png", ".webp")
                )
            ]

            if len(images) > 0:
                return target

    return None


TRAIN_DIR = choose_folder(train_candidates, "normal")
VAL_DIR = choose_folder(validation_candidates, "normal")
TEST_DIR = choose_folder(test_candidates, "normal")

# original_untouched directly contains images
ORIGINAL_DIR = None

for folder in original_candidates:

    images = [
        f for f in os.listdir(folder)
        if f.lower().endswith(
            (".jpg", ".jpeg", ".png", ".webp")
        )
    ]

    if len(images) > 0:
        ORIGINAL_DIR = folder
        break


# ------------------------------------------------------------
# Image loader
# ------------------------------------------------------------

def list_images(directory):

    if directory is None:
        return []

    return sorted([
        os.path.join(directory, f)
        for f in os.listdir(directory)
        if f.lower().endswith(
            (".jpg", ".jpeg", ".png", ".webp")
        )
    ])


# ------------------------------------------------------------
# Load datasets
# ------------------------------------------------------------

train_files = list_images(TRAIN_DIR)
val_files = list_images(VAL_DIR)
test_files = list_images(TEST_DIR)
original_files = list_images(ORIGINAL_DIR)


# ------------------------------------------------------------
# FINAL PATHS
# ------------------------------------------------------------

print("\n" + "="*60)
print("DETECTED DATASET PATHS")
print("="*60)

print("TRAIN:")
print(TRAIN_DIR)

print("\nVALIDATION:")
print(VAL_DIR)

print("\nTEST:")
print(TEST_DIR)

print("\nORIGINAL:")
print(ORIGINAL_DIR)


# ------------------------------------------------------------
# Dataset counts
# ------------------------------------------------------------

print("\n" + "="*60)
print("NSSC HiRISE DATASET SUMMARY")
print("="*60)

print("Train images       :", len(train_files))
print("Validation images  :", len(val_files))
print("Test images        :", len(test_files))
print("Original images    :", len(original_files))

print("="*60)


# ------------------------------------------------------------
# Sanity check
# ------------------------------------------------------------

if len(train_files) == 0:
    raise RuntimeError(
        "TRAIN DATASET NOT FOUND. Check the detected paths above."
    )

if len(val_files) == 0:
    raise RuntimeError(
        "VALIDATION DATASET NOT FOUND."
    )

if len(test_files) == 0:
    raise RuntimeError(
        "TEST DATASET NOT FOUND."
    )

print("\n✓✓ DATASET LOADED SUCCESSFULLY ✓✓")


# ------------------------------------------------------------
# Samples
# ------------------------------------------------------------

print("\nTRAIN samples:")
for f in train_files[:5]:
    print(" ", f)

print("\nVALIDATION samples:")
for f in val_files[:5]:
    print(" ", f)

print("\nTEST samples:")
for f in test_files[:5]:
    print(" ", f)

# ============================================================
# LOAD IMAGE FILES
# ============================================================

def list_jpgs(directory):
    return sorted([
        os.path.join(directory, f)
        for f in os.listdir(directory)
        if f.lower().endswith(".jpg")
    ])


train_files = list_jpgs(TRAIN_DIR)
val_files   = list_jpgs(VAL_DIR)
test_files  = list_jpgs(TEST_DIR)

print("Train images:", len(train_files))
print("Validation images:", len(val_files))
print("Test images:", len(test_files))

# ============================================================
# IMAGE LOADING
# ============================================================

def load_split(file_list, target_size=(227, 227)):

    arr = np.empty(
        (
            len(file_list),
            target_size[0],
            target_size[1],
            1
        ),
        dtype=np.float32
    )

    for i, fp in enumerate(file_list):

        img = Image.open(fp).convert("L")

        if img.size != target_size:
            img = img.resize(target_size)

        arr[i, :, :, 0] = (
            np.asarray(img, dtype=np.float32) / 255.0
        )

    return arr


X_train = load_split(train_files)
X_val   = load_split(val_files)
X_test  = load_split(test_files)

print("X_train:", X_train.shape)
print("X_val  :", X_val.shape)
print("X_test :", X_test.shape)

import os

# ============================================================
# METADATA
# ============================================================

# The DATASET_ROOT variable is currently pointing to the zip file.
# We need to adjust it to point to the actual extracted directory where metadata files reside.
# From the kernel state and previous cell outputs, the actual root is within EXTRACT_DIR.
METADATA_BASE_DIR = os.path.join(EXTRACT_DIR, "NSSC_HiRISE")

train_meta = pd.read_csv(
    os.path.join(METADATA_BASE_DIR, "train", "metadata.csv")
)

val_meta = pd.read_csv(
    os.path.join(METADATA_BASE_DIR, "validation", "metadata.csv")
)

test_meta = pd.read_csv(
    os.path.join(METADATA_BASE_DIR, "test", "metadata.csv")
)

source_mapping = pd.read_csv(
    os.path.join(
        METADATA_BASE_DIR,
        "source_groups",
        "source_group_mapping.csv"
    )
)

print("Train metadata:", train_meta.shape)
print("Val metadata  :", val_meta.shape)
print("Test metadata :", test_meta.shape)
print("Source mapping:", source_mapping.shape)

# ============================================================
# TF.DATA DATASETS
# ============================================================

train_ds = (
    tf.data.Dataset
    .from_tensor_slices((X_train, X_train))
    .shuffle(len(X_train), seed=42)
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

val_ds = (
    tf.data.Dataset
    .from_tensor_slices((X_val, X_val))
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

test_ds = (
    tf.data.Dataset
    .from_tensor_slices((X_test, X_test))
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

print("Datasets ready.")

# ============================================================
# V2 RECONSTRUCTION LOSS
# MSE + SSIM
# ============================================================

def v2_reconstruction_loss(y_true, y_pred):

    # Pixel-level reconstruction error
    mse = tf.reduce_mean(
        tf.square(y_true - y_pred),
        axis=[1, 2, 3]
    )

    # Structural similarity
    ssim = tf.image.ssim(
        y_true,
        y_pred,
        max_val=1.0
    )

    # Convert SSIM into structural error
    ssim_loss = 1.0 - ssim

    # Combined loss
    loss = (
        0.7 * mse
        + 0.3 * ssim_loss
    )

    return tf.reduce_mean(loss)

# ============================================================
# V2 IMPROVED CNN AUTOENCODER
# ============================================================

def build_v2_autoencoder():

    # --------------------------------------------------------
    # ENCODER
    # --------------------------------------------------------

    encoder_input = keras.Input(
        shape=INPUT_SHAPE,
        name="image_input"
    )

    x = layers.Conv2D(
        32,
        3,
        strides=2,
        padding="same",
        activation="relu",
        name="enc_conv1"
    )(encoder_input)

    x = layers.BatchNormalization(
        name="enc_bn1"
    )(x)

    x = layers.Conv2D(
        64,
        3,
        strides=2,
        padding="same",
        activation="relu",
        name="enc_conv2"
    )(x)

    x = layers.BatchNormalization(
        name="enc_bn2"
    )(x)

    x = layers.Conv2D(
        128,
        3,
        strides=2,
        padding="same",
        activation="relu",
        name="enc_conv3"
    )(x)

    x = layers.BatchNormalization(
        name="enc_bn3"
    )(x)

    x = layers.Conv2D(
        256,
        3,
        strides=2,
        padding="same",
        activation="relu",
        name="enc_conv4"
    )(x)

    x = layers.BatchNormalization(
        name="enc_bn4"
    )(x)

    # Additional feature extraction
    x = layers.Conv2D(
        256,
        3,
        padding="same",
        activation="relu",
        name="enc_conv5"
    )(x)

    x = layers.GlobalAveragePooling2D(
        name="global_pool"
    )(x)

    latent = layers.Dense(
        LATENT_DIM,
        activation=None,
        name="latent_vector"
    )(x)

    encoder = keras.Model(
        encoder_input,
        latent,
        name="V2_Encoder"
    )

    # --------------------------------------------------------
    # DECODER
    # --------------------------------------------------------

    decoder_input = keras.Input(
        shape=(LATENT_DIM,),
        name="latent_input"
    )

    x = layers.Dense(
        15 * 15 * 256,
        activation="relu",
        name="dec_dense"
    )(decoder_input)

    x = layers.Reshape(
        (15, 15, 256),
        name="dec_reshape"
    )(x)

    x = layers.Conv2DTranspose(
        256,
        3,
        strides=2,
        padding="same",
        activation="relu",
        name="dec_deconv1"
    )(x)

    x = layers.BatchNormalization(
        name="dec_bn1"
    )(x)

    x = layers.Conv2DTranspose(
        128,
        3,
        strides=2,
        padding="same",
        activation="relu",
        name="dec_deconv2"
    )(x)

    x = layers.BatchNormalization(
        name="dec_bn2"
    )(x)

    x = layers.Conv2DTranspose(
        64,
        3,
        strides=2,
        padding="same",
        activation="relu",
        name="dec_deconv3"
    )(x)

    x = layers.BatchNormalization(
        name="dec_bn3"
    )(x)

    x = layers.Conv2DTranspose(
        32,
        3,
        strides=2,
        padding="same",
        activation="relu",
        name="dec_deconv4"
    )(x)

    x = layers.BatchNormalization(
        name="dec_bn4"
    )(x)

    x = layers.Resizing(
        227,
        227,
        interpolation="bilinear",
        name="output_resize"
    )(x)

    decoder_output = layers.Conv2D(
        1,
        3,
        padding="same",
        activation="sigmoid",
        name="reconstruction"
    )(x)

    decoder = keras.Model(
        decoder_input,
        decoder_output,
        name="V2_Decoder"
    )

    # --------------------------------------------------------
    # FULL AUTOENCODER
    # --------------------------------------------------------

    autoencoder_input = keras.Input(
        shape=INPUT_SHAPE,
        name="autoencoder_input"
    )

    latent_vector = encoder(
        autoencoder_input
    )

    reconstruction = decoder(
        latent_vector
    )

    autoencoder = keras.Model(
        autoencoder_input,
        reconstruction,
        name="NSSC_HiRISE_V2"
    )

    return encoder, decoder, autoencoder


encoder_v2, decoder_v2, autoencoder_v2 = (
    build_v2_autoencoder()
)

# ============================================================
# V2 SHAPE CHECK
# ============================================================

test_input = X_train[:2]

test_latent = encoder_v2.predict(
    test_input,
    verbose=0
)

test_output = autoencoder_v2.predict(
    test_input,
    verbose=0
)

print("Input shape         :", test_input.shape)
print("Latent shape        :", test_latent.shape)
print("Reconstruction shape:", test_output.shape)

assert test_latent.shape == (2, 256)
assert test_output.shape == (2, 227, 227, 1)

print("\nV2 shape test PASSED.")

# ============================================================
# V2 COMPILE
# ============================================================

autoencoder_v2.compile(
    optimizer=keras.optimizers.Adam(
        learning_rate=1e-3
    ),
    loss=v2_reconstruction_loss
)

autoencoder_v2.summary()

# ============================================================
# V2 TRAINING
# ============================================================

callbacks_v2 = [

    keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=10,
        restore_best_weights=True,
        verbose=1
    ),

    keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=5,
        min_lr=1e-6,
        verbose=1
    ),

    keras.callbacks.ModelCheckpoint(
        "/content/NSSC_HiRISE_V2.keras",
        monitor="val_loss",
        save_best_only=True,
        verbose=1
    )
]


history_v2 = autoencoder_v2.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    callbacks=callbacks_v2,
    verbose=1
)

# ============================================================
# V2 TRAINING CURVE
# ============================================================

plt.figure(figsize=(10, 5))

plt.plot(
    history_v2.history["loss"],
    label="Train Loss"
)

plt.plot(
    history_v2.history["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("MSE + SSIM Loss")
plt.title("NSSC HiRISE V2 Training Curve")
plt.legend()
plt.grid(True)

plt.show()

# ============================================================
# V2 RECONSTRUCTION
# ============================================================

X_test_recon_v2 = autoencoder_v2.predict(
    X_test,
    batch_size=32,
    verbose=1
)

# Per-image MSE
reconstruction_errors_v2 = np.mean(
    np.square(
        X_test - X_test_recon_v2
    ),
    axis=(1, 2, 3)
)

# Per-image SSIM
ssim_scores_v2 = tf.image.ssim(
    tf.convert_to_tensor(X_test),
    tf.convert_to_tensor(X_test_recon_v2),
    max_val=1.0
).numpy()

print("========================================")
print("V2 RECONSTRUCTION RESULTS")
print("========================================")

print(
    f"Mean MSE : {reconstruction_errors_v2.mean():.6f}"
)

print(
    f"Std MSE  : {reconstruction_errors_v2.std():.6f}"
)

print(
    f"Min MSE  : {reconstruction_errors_v2.min():.6f}"
)

print(
    f"Max MSE  : {reconstruction_errors_v2.max():.6f}"
)

print()

print(
    f"Mean SSIM: {ssim_scores_v2.mean():.6f}"
)

print(
    f"Min SSIM : {ssim_scores_v2.min():.6f}"
)

print(
    f"Max SSIM : {ssim_scores_v2.max():.6f}"
)

# ============================================================
# V2 RECONSTRUCTION VISUALIZATION
# ============================================================

n = 5

indices = np.random.choice(
    len(X_test),
    n,
    replace=False
)

for idx in indices:

    plt.figure(figsize=(10, 4))

    plt.subplot(1, 2, 1)

    plt.imshow(
        X_test[idx, :, :, 0],
        cmap="gray"
    )

    plt.title("Original")
    plt.axis("off")

    plt.subplot(1, 2, 2)

    plt.imshow(
        X_test_recon_v2[idx, :, :, 0],
        cmap="gray"
    )

    plt.title(
        f"V2 Reconstruction\n"
        f"MSE={reconstruction_errors_v2[idx]:.5f}\n"
        f"SSIM={ssim_scores_v2[idx]:.4f}"
    )

    plt.axis("off")

    plt.tight_layout()
    plt.show()

# ============================================================
# V2 LATENT REPRESENTATIONS
# ============================================================

Z_train_v2 = encoder_v2.predict(
    X_train,
    batch_size=32,
    verbose=1
)

Z_val_v2 = encoder_v2.predict(
    X_val,
    batch_size=32,
    verbose=1
)

Z_test_v2 = encoder_v2.predict(
    X_test,
    batch_size=32,
    verbose=1
)

print("========================================")
print("V2 LATENT REPRESENTATIONS")
print("========================================")

print("Z_train_v2:", Z_train_v2.shape)
print("Z_val_v2  :", Z_val_v2.shape)
print("Z_test_v2 :", Z_test_v2.shape)

# ============================================================
# V2 ISOLATION FOREST
# ============================================================

from sklearn.ensemble import IsolationForest

iso_forest_v2 = IsolationForest(
    n_estimators=300,
    contamination="auto",
    random_state=42,
    n_jobs=-1
)

iso_forest_v2.fit(Z_train_v2)

# sklearn raw scores
train_if_raw_v2 = iso_forest_v2.score_samples(
    Z_train_v2
)

val_if_raw_v2 = iso_forest_v2.score_samples(
    Z_val_v2
)

test_if_raw_v2 = iso_forest_v2.score_samples(
    Z_test_v2
)

# Convert:
# higher = more anomalous
train_novelty_v2 = -train_if_raw_v2
val_novelty_v2   = -val_if_raw_v2
test_novelty_v2  = -test_if_raw_v2


print("========================================")
print("V2 ISOLATION FOREST")
print("========================================")

print(
    f"Train Mean: {train_novelty_v2.mean():.6f}"
)

print(
    f"Train Std : {train_novelty_v2.std():.6f}"
)

print(
    f"Test Mean : {test_novelty_v2.mean():.6f}"
)

print(
    f"Test Std  : {test_novelty_v2.std():.6f}"
)

print(
    f"Test Min  : {test_novelty_v2.min():.6f}"
)

print(
    f"Test Max  : {test_novelty_v2.max():.6f}"
)

# ============================================================
# V2 STATISTICAL THRESHOLDS
# ============================================================

if_threshold_v2 = (
    train_novelty_v2.mean()
    + 2 * train_novelty_v2.std()
)

recon_threshold_v2 = (
    reconstruction_errors_v2.mean()
    + 2 * reconstruction_errors_v2.std()
)

print("========================================")
print("V2 ANOMALY THRESHOLDS")
print("========================================")

print(
    f"Isolation Forest threshold : "
    f"{if_threshold_v2:.6f}"
)

print(
    f"Reconstruction threshold   : "
    f"{recon_threshold_v2:.6f}"
)

# ============================================================
# V2 ANOMALY ANALYSIS
# ============================================================

recon_anomaly_v2 = (
    reconstruction_errors_v2
    > recon_threshold_v2
)

if_anomaly_v2 = (
    test_novelty_v2
    > if_threshold_v2
)


results_v2 = pd.DataFrame({

    "filename":
        test_meta["filename"].values,

    "source_id":
        test_meta["source_id"].values,

    "group_id":
        test_meta["group_id"].values,

    "augmentation":
        test_meta["augmentation"].values,

    "reconstruction_mse":
        reconstruction_errors_v2,

    "ssim":
        ssim_scores_v2,

    "if_novelty":
        test_novelty_v2,

    "recon_anomaly":
        recon_anomaly_v2,

    "if_anomaly":
        if_anomaly_v2
})


results_v2["anomaly_evidence"] = (
    results_v2["recon_anomaly"].astype(int)
    +
    results_v2["if_anomaly"].astype(int)
)


results_v2 = results_v2.sort_values(
    by=[
        "anomaly_evidence",
        "if_novelty",
        "reconstruction_mse"
    ],
    ascending=[
        False,
        False,
        False
    ]
).reset_index(drop=True)


# Remove duplicate underlying groups
top5_v2 = (
    results_v2
    .drop_duplicates("group_id")
    .head(5)
)


print("========================================")
print("V2 TOP 5 SUSPECTED ANOMALIES")
print("========================================")

display(
    top5_v2[
        [
            "filename",
            "source_id",
            "group_id",
            "augmentation",
            "reconstruction_mse",
            "ssim",
            "if_novelty",
            "anomaly_evidence"
        ]
    ]
)


print("\n========================================")
print("V2 ANOMALY COUNTS")
print("========================================")

print(
    "Reconstruction anomalies:",
    recon_anomaly_v2.sum()
)

print(
    "Isolation Forest anomalies:",
    if_anomaly_v2.sum()
)

print(
    "Both methods agree:",
    (
        recon_anomaly_v2
        & if_anomaly_v2
    ).sum()
)

# ============================================================
# SAVE V2 RESULTS
# ============================================================

results_v2.to_csv(
    "/content/NSSC_HiRISE_V2_results.csv",
    index=False
)

np.save(
    "/content/NSSC_HiRISE_V2_Z_train.npy",
    Z_train_v2
)

np.save(
    "/content/NSSC_HiRISE_V2_Z_test.npy",
    Z_test_v2
)

print("V2 results saved successfully.")

print("=" * 60)
print("V2 RESULTS")
print("=" * 60)

print("\nTest MSE:")
print("Mean:", reconstruction_errors_v2.mean())
print("Std :", reconstruction_errors_v2.std())
print("Min :", reconstruction_errors_v2.min())
print("Max :", reconstruction_errors_v2.max())

print("\nSSIM:")
print("Mean:", ssim_scores_v2.mean())
print("Min :", ssim_scores_v2.min())
print("Max :", ssim_scores_v2.max())

print("\nIsolation Forest:")
print("Threshold:", if_threshold_v2)
print("Anomalies:", if_anomaly_v2.sum())

print("\nReconstruction:")
print("Threshold:", recon_threshold_v2)
print("Anomalies:", recon_anomaly_v2.sum())

print("\nBoth methods:")
print("Agree:", (if_anomaly_v2 & recon_anomaly_v2).sum())

print("\nTop 10:")
display(results_v2.head(10))

import os
import zipfile
from google.colab import files

ZIP_PATH = "/content/NSSC_HiRISE_V2_BACKUP.zip"

targets = [
    "/content/NSSC_HiRISE_V2.keras",
    "/content/NSSC_HiRISE_V2_results.csv",
    "/content/NSSC_HiRISE_V2_Z_train.npy",
    "/content/NSSC_HiRISE_V2_Z_test.npy",
    "/content/NSSC_HiRISE_V2_Top5",
    "/content/NSSC_V2_Top5",
]

found = []

for path in targets:
    if os.path.isfile(path):
        found.append(path)

    elif os.path.isdir(path):
        for root, dirs, filenames in os.walk(path):
            for filename in filenames:
                found.append(os.path.join(root, filename))

print("=" * 60)
print("V2 FILES FOUND")
print("=" * 60)

for f in found:
    print("✓", f)

if not found:
    print("❌ V2 files nahi mili.")
else:
    if os.path.exists(ZIP_PATH):
        os.remove(ZIP_PATH)

    with zipfile.ZipFile(
        ZIP_PATH,
        "w",
        zipfile.ZIP_DEFLATED
    ) as z:

        for f in found:
            z.write(
                f,
                arcname=os.path.relpath(f, "/content")
            )

    print("\n" + "=" * 60)
    print("V2 BACKUP READY")
    print("=" * 60)

    print("ZIP:", ZIP_PATH)
    print("Files:", len(found))

    files.download(ZIP_PATH)